GENDER_MALE = 0
GENDER_MALE_TEXT = 'male'
GENDER_FEMALE = 1
GENDER_FEMALE_TEXT = 'female'
GENDER_OTHER = 2
GENDER_OTHER_TEXT = 'third gender'
GENDER = (
    (GENDER_MALE, GENDER_MALE_TEXT),
    (GENDER_FEMALE, GENDER_FEMALE_TEXT),
    (GENDER_OTHER, GENDER_OTHER_TEXT)
)